name: Integracion Continua y Entrega

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas automatizadas
        run: npm test

      - name: Ejecutar build
        run: npm run build

      - name: Subir artifact para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  notify-success:
    if: success() && github.event_name == 'push'
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Enviar email de despliegue exitoso
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI/CD OK - Aplicacion desplegada"
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          body: |
            La pipeline finalizo correctamente.

            Repositorio: ${{ github.repository }}
            Commit: ${{ github.sha }}

            URL:
            https://sandcd.github.io/ci-demo/

  notify-failure:
    if: failure()
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Enviar email de fallo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI/CD FALLO"
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          body: |
            La pipeline fallo.

            Repositorio: ${{ github.repository }}
            Commit: ${{ github.sha }}

            Revisar GitHub Actions.